"use client";

import DocumentView from "@/app/(admin)/admin/relocations/[id]/_components/DocumentView";
import { domesticDemoDocumentV2 } from "../sample/domesticDemoData";

const headerColor = "#18453b";

export default function DomesticSampleReportPage() {
  return (
    <div className="min-h-screen bg-surface">
      <nav className="bg-white border-b border-border px-6 py-4 flex items-center justify-between no-print sticky top-0 z-50">
        <a href="/"><img src="/settlyou-logo-dark.png" alt="Settl" className="h-7" /></a>
        <a href="/pricing" className="text-xs font-semibold px-4 py-2 rounded-lg border border-brand-200 text-brand-600 hover:bg-brand-50 transition-colors">
          Request a quote →
        </a>
      </nav>

      <div className="no-print" style={{ background: headerColor }}>
        <div className="max-w-4xl mx-auto px-4 pt-10 pb-8">
          <div className="flex items-center gap-3 mb-6">
            <img src="/settlyou-logo-white.png" alt="Settlyou" className="h-6 object-contain" />
          </div>
          <h1 className="text-3xl font-bold text-white mb-2 leading-tight">
            Michigan State University
            <br />
            <span className="text-white opacity-70">Student Relocation Guide</span>
          </h1>
          <p className="text-white opacity-60 text-sm max-w-xl leading-relaxed">
            Every incoming student gets a personalized guide — built around who they are, where they're coming from, and what they need to hit the ground running in East Lansing.
          </p>
        </div>
      </div>

      <div className="max-w-4xl mx-auto px-4 py-8">
        <DocumentView content={domesticDemoDocumentV2} />
      </div>

      <div className="no-print" style={{ background: headerColor }}>
        <div className="max-w-4xl mx-auto px-4 py-16 text-center">
          <p className="text-xs font-bold uppercase tracking-widest text-white/60 mb-3">Powered by Settlyou</p>
          <h2 className="text-3xl font-bold text-white mb-3">Want guides like this for every incoming student?</h2>
          <p className="text-white/70 max-w-lg mx-auto mb-10 leading-relaxed text-sm">
            Every student gets their own guide — personalized to their background, destination, and goals.
          </p>
          <a href="/pricing" className="inline-block px-8 py-3 rounded-lg text-sm font-semibold bg-white hover:bg-white/90 transition-colors" style={{ color: headerColor }}>
            Request a quote
          </a>
        </div>
      </div>

      <footer className="border-t border-border px-6 py-4 text-center text-xs text-muted no-print">
        This is a sample document generated by Settlyou · Not a real relocation package
      </footer>
    </div>
  );
}
