// Add a new client by duplicating an entry and updating the fields.
// NOTE: primaryColor must have sufficient contrast with white text.

export const PITCH_CLIENTS = [
  {
    slug: "sample",
    name: "Your University",
    shortName: "Your Program",
    primaryColor: "#15803d",
    logoUrl: null,
    sport: null,
    contact: null,
    role: null,
    city: null,
    division: null,
    estimatedStudents: null,
    type: "general",
  },
  {
    slug: "fau",
    name: "Florida Atlantic University",
    shortName: "FAU",
    primaryColor: "#003366",
    logoUrl: "/Florida_Atlantic_Owls_logo.svg.png",
    sport: "Football",
    contact: null,
    role: "Athletics Director",
    city: "Boca Raton",
    division: "NCAA D1",
    estimatedStudents: 120,
    type: "athletics",
  },
  {
    slug: "stanford",
    name: "Stanford University",
    shortName: "Stanford",
    primaryColor: "#8C1515",
    logoUrl: "/stanford-logo.png",
    sport: null,
    contact: null,
    role: "Athletics Director",
    city: "Palo Alto",
    division: "NCAA D1",
    estimatedStudents: 200,
    type: "athletics",
  },
  {
    slug: "csu-pueblo",
    name: "Colorado State University Pueblo",
    shortName: "CSU Pueblo",
    primaryColor: "#C41425",
    logoUrl: null,
    sport: null,
    contact: null,
    role: "Athletics Director",
    city: "Pueblo",
    division: "NCAA D2",
    estimatedStudents: 80,
    type: "athletics",
  },
  {
    slug: "miami-admissions",
    name: "University of Miami",
    shortName: "UM",
    primaryColor: "#f47321",
    logoUrl: null,
    sport: null,
    contact: null,
    role: "Director of Admissions",
    city: "Coral Gables",
    division: null,
    estimatedStudents: 800,
    type: "admissions",
  },
];

export function getClientBySlug(slug) {
  return PITCH_CLIENTS.find((c) => c.slug === slug) ?? null;
}
