export const dynamic = 'force-dynamic';
import { createAdminClient } from "@/lib/supabase/admin";
import { notFound } from "next/navigation";
import DocumentView from "@/app/(admin)/admin/relocations/[id]/_components/DocumentView";
import PrintButton from "./PrintButton";
import ReportTracker from "./ReportTracker";
import { getSportDocTypes } from "@/lib/documents/types";

export default async function AthleteReportPage({ params }) {
  const { token } = await params;
  const admin = createAdminClient();

  const { data: request } = await admin
    .from("requests")
    .select("*, documents(*), clubs(logo_url, primary_color, plan, custom_notes, custom_links, club_documents)")
    .eq("athlete_link_token", token)
    .in("status", ["under_review", "delivered", "approved"])
    .single();

  if (!request) notFound();

  const document = request.documents?.[0];
  const isPremium = request.clubs?.plan === "premium";

  // Fetch sport doc config for required docs list
  const { data: sportConfig } = request.sport && request.club_id ? await admin
    .from("sport_document_config")
    .select("disabled_base_docs, custom_docs")
    .eq("club_id", request.club_id)
    .eq("sport", request.sport)
    .single() : { data: null };

  const requiredDocs = getSportDocTypes(sportConfig ?? null);
  const uploadUrl = request.upload_token ? `/upload/${request.upload_token}` : null;

  return (
    <div className="min-h-screen bg-surface">
      <ReportTracker requestId={request.id} clubId={request.club_id} isPremium={isPremium} />
      <nav className="bg-white border-b border-border px-6 py-4 flex items-center justify-between">
        <img src="/settlyou-logo-dark.png" alt="Settl" className="h-7" />
        <div className="flex items-center gap-4">
          <span className="text-sm text-muted">Relocation Guide · {request.athlete_name}</span>
          <PrintButton />
        </div>
      </nav>

      {/* Print cover — only visible in PDF */}
      <div className="print-only" style={{ pageBreakAfter: "always", padding: "3cm 0 2cm", textAlign: "center", borderBottom: "2px solid #e4e4e7", marginBottom: "1cm" }}>
        <img src="/settlyou-logo-dark.png" alt="Settl" style={{ height: "36px", margin: "0 auto 2cm" }} />
        <div style={{ fontSize: "28pt", fontWeight: "700", color: "#09090b", marginBottom: "0.4cm" }}>{request.athlete_name}</div>
        <div style={{ fontSize: "13pt", color: "#52525b", marginBottom: "0.8cm" }}>Relocation Guide</div>
        {request.clubs?.name && <div style={{ fontSize: "11pt", color: "#71717a" }}>{request.clubs.name}</div>}
        <div style={{ fontSize: "10pt", color: "#a1a1aa", marginTop: "0.4cm" }}>
          Generated by Settlyou · {new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}
        </div>
      </div>

      <div className="max-w-4xl mx-auto px-4 py-10">
        {document ? (
          <DocumentView content={{
            ...document.content,
            meta: {
              ...document.content?.meta,
              ...(isPremium && request.clubs?.logo_url && { club_logo_url: request.clubs.logo_url }),
              ...(isPremium && request.clubs?.primary_color && { club_primary_color: request.clubs.primary_color }),
            },
            university_notes: request.clubs?.custom_notes || null,
            university_links: request.clubs?.custom_links || null,
            university_documents: request.clubs?.club_documents || null,
            upload_url: uploadUrl,
            required_docs: requiredDocs,
          }} />
        ) : (
          <div className="text-center py-20 text-muted text-sm">
            Your relocation guide is being prepared. Check back soon.
          </div>
        )}
      </div>

      <footer className="border-t border-border px-6 py-4 text-center text-xs text-muted">
        Prepared exclusively for {request.athlete_name} by Settlyou · Confidential
      </footer>
    </div>
  );
}
