"use client";

import DocumentView from "@/app/(admin)/admin/relocations/[id]/_components/DocumentView";
import { collegeDemoDocumentV2 } from "../sample/collegeDemoData";

const headerColor = "#16a34a";
const ctaColor = "#16a34a";

export default function CollegeSampleReportPage() {
  return (
    <div className="min-h-screen bg-surface">

      {/* Nav */}
      <nav className="bg-white border-b border-border px-6 py-4 flex items-center justify-between no-print sticky top-0 z-50">
        <a href="/">
          <img src="/settlyou-logo-dark.png" alt="Settl" className="h-7" />
        </a>
        <a
          href="/pricing"
          className="text-xs font-semibold px-4 py-2 rounded-lg border border-brand-200 text-brand-600 hover:bg-brand-50 transition-colors"
        >
          Request a quote →
        </a>
      </nav>

      {/* Hero header */}
      <div className="no-print" style={{ background: headerColor }}>
        <div className="max-w-4xl mx-auto px-4 pt-10 pb-8">
          {/* FAU + Settlyou lockup */}
          <div className="flex items-center gap-3 mb-6">
            <img
              src="/Florida_Atlantic_Owls_logo.svg.png"
              alt="Florida Atlantic University"
              className="w-12 h-12 object-contain bg-white rounded-xl p-1.5 shrink-0"
            />
            <div className="text-white opacity-40 text-2xl font-light">×</div>
            <img
              src="/settlyou-logo-white.png"
              alt="Settlyou"
              className="h-6 object-contain"
            />
          </div>

          <h1 className="text-3xl font-bold text-white mb-2 leading-tight">
            Florida Atlantic University
            <br />
            <span className="text-white opacity-70">Student Relocation Guide</span>
          </h1>
          <p className="text-white opacity-60 text-sm max-w-xl leading-relaxed">
            Every incoming student gets a personalized guide — built around who they are, where they're coming from, and what they need to hit the ground running in Boca Raton.
          </p>
        </div>
      </div>

      {/* Document */}
      <div className="max-w-4xl mx-auto px-4 py-8">
        <DocumentView content={{
          ...collegeDemoDocumentV2,
          meta: {
            ...collegeDemoDocumentV2.meta,
            club_logo_url: "/Florida_Atlantic_Owls_logo.svg.png",
            club_primary_color: "#003366",
          },
          university_notes: "Welcome to the FAU Owls family! Before you arrive, make sure you've completed your SEVIS check-in with the International Student Office (Building 96, Room 129). Your compliance forms and pre-participation physical must be on file with Sports Medicine before your first team practice. Housing applications for on-campus residents close July 15th — submit yours as soon as possible. If you have any questions, reach out to your academic advisor — they're expecting you.",
          university_links: [
            { label: "FAU Athlete Portal", url: "https://fausports.com" },
            { label: "International Student Services", url: "https://www.fau.edu/international" },
            { label: "NCAA Eligibility Center", url: "https://web3.ncaa.org/ecwr3/" },
          ],
        }} />
      </div>

      {/* CTA footer */}
      <div className="no-print" style={{ background: ctaColor }}>
        <div className="max-w-4xl mx-auto px-4 py-16 text-center">
          <p className="text-xs font-bold uppercase tracking-widest text-white/60 mb-3">Powered by Settlyou</p>
          <h2 className="text-3xl font-bold text-white mb-3">
            Want guides like this for every incoming student?
          </h2>
          <p className="text-white/70 max-w-lg mx-auto mb-10 leading-relaxed text-sm">
            Every student gets their own guide — personalized to their background, destination, visa status, and goals. NCAA eligibility, banking, housing, community, and everything in between.
          </p>
          <div className="flex flex-col sm:flex-row gap-3 justify-center">
            <a
              href="/pricing"
              className="inline-block px-8 py-3 rounded-lg text-sm font-semibold bg-white transition-colors hover:bg-white/90"
              style={{ color: ctaColor }}
            >
              Request a quote
            </a>
            <a
              href="/"
              className="inline-block px-8 py-3 rounded-lg text-sm font-semibold border border-white/30 text-white hover:bg-white/10 transition-colors"
            >
              Learn how it works
            </a>
          </div>
        </div>
      </div>

      <footer className="border-t border-border px-6 py-4 text-center text-xs text-muted no-print">
        This is a sample document generated by Settlyou · Not a real relocation package
      </footer>
    </div>
  );
}
