import DocumentView from "@/app/(admin)/admin/relocations/[id]/_components/DocumentView";
import { collegeDemoDocument } from "../sample/collegeDemoData";

export default function CollegeSampleReportPage() {
  return (
    <div className="min-h-screen bg-surface">
      <nav className="bg-white border-b border-border px-6 py-4 flex items-center justify-between no-print">
        <a href="/"><img src="/settlyou-logo.png" alt="Settl" className="h-8 rounded-md" /></a>
        <div className="flex items-center bg-surface border border-border rounded-lg p-0.5 gap-0.5">
          <a
            href="/report/sample-college-essentials"
            className="px-4 py-1.5 rounded-md text-sm font-medium text-muted hover:text-foreground transition-colors"
          >
            Essentials
          </a>
          <span className="px-4 py-1.5 rounded-md text-sm font-semibold bg-brand-600 text-white">
            Premium
          </span>
        </div>
        <a href="/pricing" className="text-xs font-semibold px-4 py-2 rounded-lg border border-brand-200 text-brand-600 hover:bg-brand-50 transition-colors">View pricing →</a>
      </nav>

      <div className="max-w-4xl mx-auto px-4 py-10">
        <DocumentView content={collegeDemoDocument} />
      </div>

      <footer className="border-t border-border px-6 py-4 text-center text-xs text-muted no-print">
        This is a sample document generated by Settlyou · Not a real relocation package
      </footer>
    </div>
  );
}
