import DocumentView from "@/app/(admin)/admin/relocations/[id]/_components/DocumentView";
import { demoDocument } from "./demoData";

export default function SampleReportPage() {
  return (
    <div className="min-h-screen bg-surface">
      {/* Demo banner */}
      <div className="bg-brand-600 text-white text-center py-3 px-6 no-print">
        <p className="text-sm font-medium">
          This is a sample Settl relocation guide —{" "}
          <a href="/" className="underline hover:no-underline font-semibold">
            learn more about Settl →
          </a>
        </p>
      </div>

      <nav className="bg-white border-b border-border px-6 py-4 flex items-center justify-between no-print">
        <img src="/settlyou-logo.png" alt="Settl" className="h-8 rounded-md" />
        <span className="text-sm text-muted">Sample Report · Gabriel Santos</span>
      </nav>

      <div className="max-w-4xl mx-auto px-4 py-10">
        <DocumentView content={demoDocument} />
      </div>

      <footer className="border-t border-border px-6 py-4 text-center text-xs text-muted no-print">
        This is a sample document generated by Settl · Not a real relocation package
      </footer>
    </div>
  );
}
